"""Port interface for LLM-powered President deliberation.

Defines the protocol for Presidents to analyze Ratified Intent Packets
and produce either PortfolioContributions or NoActionAttestations.

Constitutional Compliance:
- CT-11: All LLM calls logged, failures reported
- CT-12: Contributions traceable to source motions and portfolio identity

Schema Version: 2.0
- Enhanced DeliberationContext with full motion/review artifacts
- Added trace_metadata for LLM provenance tracking
- Added generated_by field for origin tracking (llm vs manual)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from src.domain.models.executive_planning import (
        NoActionAttestation,
        PortfolioContribution,
        PortfolioIdentity,
        RatifiedIntentPacket,
    )


@dataclass
class TraceMetadata:
    """Metadata for LLM call tracing and provenance.

    Records details about the LLM invocation for auditing,
    debugging, and constitutional compliance (CT-11).
    """

    timestamp: str  # ISO8601 when deliberation started
    model: str  # Model identifier (e.g., "gpt-4", "claude-3-opus")
    provider: str  # Provider (e.g., "openai", "anthropic", "ollama")
    duration_ms: int  # Total deliberation time
    prompt_tokens: int | None = None  # Input token count (if available)
    completion_tokens: int | None = None  # Output token count (if available)
    temperature: float | None = None  # Temperature setting used
    request_id: str | None = None  # Provider request ID for tracing

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "model": self.model,
            "provider": self.provider,
            "duration_ms": self.duration_ms,
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
            "temperature": self.temperature,
            "request_id": self.request_id,
        }


@dataclass
class DeliberationContext:
    """Context for President deliberation.

    Schema Version 2.0 adds:
    - ratified_motion: Full motion data from RatifiedIntentPacket
    - review_artifacts: Triage/aggregation/dissent from review pipeline
    - assignment_record: Executive assignment with affected portfolios
    - portfolio_labels: Human-readable portfolio names
    """

    # Core identifiers
    cycle_id: str
    motion_id: str
    motion_title: str
    motion_text: str

    # Motion context
    constraints: list[str]
    affected_portfolios: list[str]
    plan_owner_portfolio_id: str
    response_deadline: str

    # v2: Enhanced context for better LLM deliberation
    ratified_motion: dict[str, Any] = field(default_factory=dict)
    review_artifacts: dict[str, Any] = field(default_factory=dict)
    assignment_record: dict[str, Any] = field(default_factory=dict)
    portfolio_labels: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "cycle_id": self.cycle_id,
            "motion_id": self.motion_id,
            "motion_title": self.motion_title,
            "motion_text": self.motion_text,
            "constraints": self.constraints,
            "affected_portfolios": self.affected_portfolios,
            "plan_owner_portfolio_id": self.plan_owner_portfolio_id,
            "response_deadline": self.response_deadline,
            "ratified_motion": self.ratified_motion,
            "review_artifacts": self.review_artifacts,
            "assignment_record": self.assignment_record,
            "portfolio_labels": self.portfolio_labels,
        }


class GeneratedBy:
    """Origin tracking constants for deliberation results."""

    LLM = "llm"  # Generated by LLM deliberation
    MANUAL = "manual"  # Loaded from manual inbox artifacts
    HYBRID = "hybrid"  # LLM-generated, manually edited


@dataclass
class DeliberationResult:
    """Result of President deliberation on a motion.

    Schema Version 2.0 adds:
    - generated_by: Track origin (llm, manual, hybrid)
    - trace_metadata: LLM invocation details for provenance
    """

    portfolio_id: str
    president_name: str
    contributed: bool
    contribution: PortfolioContribution | None = None
    attestation: NoActionAttestation | None = None
    deliberation_notes: str = ""
    duration_ms: int = 0

    # v2: Origin and provenance tracking
    generated_by: str = GeneratedBy.LLM
    trace_metadata: TraceMetadata | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        result = {
            "portfolio_id": self.portfolio_id,
            "president_name": self.president_name,
            "contributed": self.contributed,
            "deliberation_notes": self.deliberation_notes,
            "duration_ms": self.duration_ms,
            "generated_by": self.generated_by,
        }

        if self.contribution:
            result["contribution"] = self.contribution.to_dict()
        if self.attestation:
            result["attestation"] = self.attestation.to_dict()
        if self.trace_metadata:
            result["trace_metadata"] = self.trace_metadata.to_dict()

        return result


class PresidentDeliberationError(Exception):
    """Base error for President deliberation failures."""


class PresidentDeliberationProtocol(ABC):
    """Protocol for LLM-powered President deliberation."""

    @abstractmethod
    async def deliberate(
        self,
        packet: RatifiedIntentPacket,
        portfolio: PortfolioIdentity,
        portfolio_scope: list[str],
        context: DeliberationContext,
    ) -> DeliberationResult:
        """Deliberate on a ratified motion from a portfolio perspective.

        The President analyzes the motion and decides whether to:
        1. Contribute tasks (PortfolioContribution) with capacity claims
        2. Attest no action needed (NoActionAttestation) with reason

        Args:
            packet: The ratified intent packet containing motion details
            portfolio: Identity of the portfolio/president making the decision
            portfolio_scope: List of domain keywords for this portfolio
            context: Additional context for the deliberation

        Returns:
            DeliberationResult with either contribution or attestation

        Raises:
            PresidentDeliberationError: If deliberation fails
        """

    @abstractmethod
    async def batch_deliberate(
        self,
        packet: RatifiedIntentPacket,
        portfolios: list[tuple[PortfolioIdentity, list[str]]],
        context: DeliberationContext,
    ) -> list[DeliberationResult]:
        """Run deliberation for multiple portfolios.

        Args:
            packet: The ratified intent packet
            portfolios: List of (PortfolioIdentity, scope) tuples
            context: Deliberation context

        Returns:
            List of DeliberationResults, one per portfolio
        """
