"""Domain models for Duke Proposal Pipeline.

Each Administrative Duke reads a finalized Executive RFP and produces a complete
implementation proposal. Duke proposals cover the entire RFP scope (not per-epic)
and include duke identity metadata plus requirement coverage traceability.

Pipeline Position:
    Legislative (Motion) -> Executive (RFP) -> Administrative (Duke Proposals) <- THIS
                                             -> Executive (Selection)          <- LATER
                                             -> Administrative (Execution)     <- DONE

Schema Versions:
    1.0: Initial version for competitive Duke proposal generation
    2.0: Markdown-first proposals with count sidecars (replaces structured JSON)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

# Schema version for Duke Proposal artifacts
DUKE_PROPOSAL_SCHEMA_VERSION = "2.0"


class ProposalStatus(str, Enum):
    """Status of a Duke's proposal."""

    GENERATED = "GENERATED"  # Successfully generated by LLM
    FAILED = "FAILED"  # LLM or parse failure
    SIMULATION = "SIMULATION"  # Generated via simulation (no LLM)


@dataclass
class DukeProposal:
    """Complete implementation proposal from a single Duke for an entire RFP.

    This is the aggregate root for Duke proposals. The full proposal body lives
    in ``proposal_markdown``; structured counts provide quick summary access
    without parsing Markdown.
    """

    # Identity
    proposal_id: str
    duke_archon_id: str
    duke_name: str
    duke_domain: str  # From archons-base.json role field
    duke_abbreviation: str  # First 4 chars uppercase for ID namespacing

    # RFP reference
    rfp_id: str  # implementation_dossier_id from the RFP
    mandate_id: str

    # Status and timing
    status: ProposalStatus
    created_at: str  # ISO8601

    # Proposal content (Markdown body + counts)
    proposal_markdown: str = ""
    tactic_count: int = 0
    risk_count: int = 0
    resource_request_count: int = 0
    requirement_coverage_count: int = 0
    deliverable_plan_count: int = 0
    assumption_count: int = 0
    constraint_count: int = 0

    # Trace metadata
    llm_model: str = ""
    llm_provider: str = ""
    failure_reason: str = ""

    schema_version: str = DUKE_PROPOSAL_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "artifact_type": "duke_proposal",
            "proposal_id": self.proposal_id,
            "duke": {
                "archon_id": self.duke_archon_id,
                "name": self.duke_name,
                "domain": self.duke_domain,
                "abbreviation": self.duke_abbreviation,
            },
            "rfp_id": self.rfp_id,
            "mandate_id": self.mandate_id,
            "status": self.status.value,
            "created_at": self.created_at,
            "counts": {
                "tactics": self.tactic_count,
                "risks": self.risk_count,
                "resource_requests": self.resource_request_count,
                "requirement_coverage": self.requirement_coverage_count,
                "deliverable_plans": self.deliverable_plan_count,
                "assumptions": self.assumption_count,
                "constraints": self.constraint_count,
            },
            "trace": {
                "llm_model": self.llm_model,
                "llm_provider": self.llm_provider,
                "failure_reason": self.failure_reason,
            },
        }

    def validate(self) -> list[str]:
        errors: list[str] = []

        if not self.proposal_id:
            errors.append("DukeProposal missing required field: proposal_id")
        if not self.duke_archon_id:
            errors.append("DukeProposal missing required field: duke_archon_id")
        if not self.duke_name:
            errors.append("DukeProposal missing required field: duke_name")
        if not self.rfp_id:
            errors.append("DukeProposal missing required field: rfp_id")
        if not self.mandate_id:
            errors.append("DukeProposal missing required field: mandate_id")
        if not self.created_at:
            errors.append("DukeProposal missing required field: created_at")

        # Generated proposals must have at least one tactic and non-empty markdown
        if self.status == ProposalStatus.GENERATED:
            if self.tactic_count < 1:
                errors.append(
                    f"Proposal {self.proposal_id}: generated proposals require at least one tactic"
                )
            if not self.proposal_markdown.strip():
                errors.append(
                    f"Proposal {self.proposal_id}: generated proposals require non-empty proposal_markdown"
                )

        return errors

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DukeProposal:
        duke = data.get("duke", {})
        trace = data.get("trace", {})
        counts = data.get("counts", {})

        return cls(
            proposal_id=data["proposal_id"],
            duke_archon_id=duke.get("archon_id", data.get("duke_archon_id", "")),
            duke_name=duke.get("name", data.get("duke_name", "")),
            duke_domain=duke.get("domain", data.get("duke_domain", "")),
            duke_abbreviation=duke.get(
                "abbreviation", data.get("duke_abbreviation", "")
            ),
            rfp_id=data.get("rfp_id", ""),
            mandate_id=data.get("mandate_id", ""),
            status=ProposalStatus(data.get("status", "GENERATED")),
            created_at=data.get("created_at", ""),
            proposal_markdown=data.get("proposal_markdown", ""),
            tactic_count=counts.get("tactics", data.get("tactic_count", 0)),
            risk_count=counts.get("risks", data.get("risk_count", 0)),
            resource_request_count=counts.get(
                "resource_requests", data.get("resource_request_count", 0)
            ),
            requirement_coverage_count=counts.get(
                "requirement_coverage", data.get("requirement_coverage_count", 0)
            ),
            deliverable_plan_count=counts.get(
                "deliverable_plans", data.get("deliverable_plan_count", 0)
            ),
            assumption_count=counts.get("assumptions", data.get("assumption_count", 0)),
            constraint_count=counts.get("constraints", data.get("constraint_count", 0)),
            llm_model=trace.get("llm_model", data.get("llm_model", "")),
            llm_provider=trace.get("llm_provider", data.get("llm_provider", "")),
            failure_reason=trace.get("failure_reason", data.get("failure_reason", "")),
            schema_version=data.get("schema_version", DUKE_PROPOSAL_SCHEMA_VERSION),
        )


@dataclass
class DukeProposalSummary:
    """Aggregate statistics for all Duke proposals on one RFP."""

    rfp_id: str
    mandate_id: str
    created_at: str
    total_proposals: int = 0
    generated_count: int = 0
    failed_count: int = 0
    simulation_count: int = 0
    total_tactics: int = 0
    total_risks: int = 0
    total_resource_requests: int = 0
    duke_names: list[str] = field(default_factory=list)
    proposals: list[dict[str, Any]] = field(default_factory=list)
    schema_version: str = DUKE_PROPOSAL_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "artifact_type": "duke_proposal_summary",
            "rfp_id": self.rfp_id,
            "mandate_id": self.mandate_id,
            "created_at": self.created_at,
            "total_proposals": self.total_proposals,
            "generated_count": self.generated_count,
            "failed_count": self.failed_count,
            "simulation_count": self.simulation_count,
            "total_tactics": self.total_tactics,
            "total_risks": self.total_risks,
            "total_resource_requests": self.total_resource_requests,
            "duke_names": self.duke_names,
            "proposals": self.proposals,
        }

    @classmethod
    def from_proposals(
        cls,
        proposals: list[DukeProposal],
        rfp_id: str,
        mandate_id: str,
        created_at: str,
    ) -> DukeProposalSummary:
        generated = sum(1 for p in proposals if p.status == ProposalStatus.GENERATED)
        failed = sum(1 for p in proposals if p.status == ProposalStatus.FAILED)
        simulation = sum(1 for p in proposals if p.status == ProposalStatus.SIMULATION)

        proposal_summaries = []
        for p in proposals:
            proposal_summaries.append(
                {
                    "proposal_id": p.proposal_id,
                    "duke_name": p.duke_name,
                    "duke_abbreviation": p.duke_abbreviation,
                    "status": p.status.value,
                    "tactic_count": p.tactic_count,
                    "risk_count": p.risk_count,
                    "resource_request_count": p.resource_request_count,
                    "requirement_coverage_count": p.requirement_coverage_count,
                    "deliverable_plan_count": p.deliverable_plan_count,
                }
            )

        return cls(
            rfp_id=rfp_id,
            mandate_id=mandate_id,
            created_at=created_at,
            total_proposals=len(proposals),
            generated_count=generated,
            failed_count=failed,
            simulation_count=simulation,
            total_tactics=sum(p.tactic_count for p in proposals),
            total_risks=sum(p.risk_count for p in proposals),
            total_resource_requests=sum(p.resource_request_count for p in proposals),
            duke_names=[p.duke_name for p in proposals],
            proposals=proposal_summaries,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DukeProposalSummary:
        return cls(
            rfp_id=data.get("rfp_id", ""),
            mandate_id=data.get("mandate_id", ""),
            created_at=data.get("created_at", ""),
            total_proposals=data.get("total_proposals", 0),
            generated_count=data.get("generated_count", 0),
            failed_count=data.get("failed_count", 0),
            simulation_count=data.get("simulation_count", 0),
            total_tactics=data.get("total_tactics", 0),
            total_risks=data.get("total_risks", 0),
            total_resource_requests=data.get("total_resource_requests", 0),
            duke_names=data.get("duke_names", []),
            proposals=data.get("proposals", []),
            schema_version=data.get("schema_version", DUKE_PROPOSAL_SCHEMA_VERSION),
        )
